name: Check Submodule Tags
on:
  schedule:
    - cron: "0 0 * * *" # Daily check
  workflow_dispatch:

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    permissions: # Job-level permissions configuration starts here
      contents: write # 'write' access to repository contents
      pull-requests: write # 'write' access to pull requests
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Get Latest Tag
        id: get-tag
        run: |
          LATEST_TAG=$(git ls-remote --tags --sort=-v:refname https://github.com/tailscale/tailscale.git | grep -vF '{}' | grep -v -- '-pre$' | head -n1 | awk -F/ '{print $3}')
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Update Submodule
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          cd tailscale
          git fetch --tags
          git checkout ${{ steps.get-tag.outputs.latest_tag }}
          cd ..
          git add tailscale
          git commit -m "chore: update submodule to ${{ steps.get-tag.outputs.latest_tag }}"
          git push
